_labels:
  app.kubernetes.io/component: example-component
  app.kubernetes.io/instance: {{ name }}-{{ release }}
  app.kubernetes.io/part-of: {{ name }}

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: 300
    nginx.ingress.kubernetes.io/proxy-read-timeout: 300
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - mydomain.com
  tls:
    - hosts:
        - mydomain.com
      secretName: {{ create_tls_secret(
                      custom_cmd=True,
                      cert='cat namespaces/playground/data/mydomain.com.crt',
                      key='cat namespaces/playground/data/mydomain.com.key') }}

secrets:
  service: {{ create_secret(custom_cmd=True, data={'my-secret': 'cat namespaces/playground/data/mysecret'}) }}
  service_2: {{ create_secret(custom_cmd=True, data={'my-secret': 'echo yolo'}) }}