apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}-{{ release }}-config
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/component: config
data:
  service.conf: {{ include_file('my-service/files/service.conf') }}