---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: {{ name }}-{{ release }}-ingress
  namespace: {{ namespace }}
  annotations:
    {% for name, value in ingress.get('annotations', deployment.get('ingress.annotations', {})).items() %}
    {{ name }}: "{{ value }}"
    {% endfor %}
  labels:
    app.kubernetes.io/component: ingress
spec:
  {% if ingress.get('tls', False) %}
  tls:
    {{ ingress.get('tls') | yaml(false) | indent(4) }}
  {% endif %}
  rules:
  {% for host in ingress.get('hosts') %}
    - host: {{ host }}
      http:
        paths:
          - backend:
              serviceName: myservice
              servicePort: http
            path: /
  {% endfor %}