site_name: adeploy

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/badges.css
  - assets/css/asciinema-player.css

extra_javascript:
  - assets/js/asciinema-player.min.js

plugins:
  - search
  - mkdocs-asciinema

nav:
  - About: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - Jinja Deployment:
    - Quickstart: 'jinja/index.md'
  - Helm Deployment:
    - Quickstart: 'helm/index.md'
    - Hooks: 'helm/hooks.md'
  - Common Tools: 'common/index.md'

# Hooks
hooks:
  - docs/hooks/badges.py