[build-system]
# Consider all git-tracked files as data-files
# https://stackoverflow.com/a/73062301
requires = [
  "setuptools>=60",
  "setuptools-scm>=8.0"
]
build-backend = "setuptools.build_meta"

# See https://setuptools-scm.readthedocs.io/en/latest/usage/
[tool.setuptools_scm]
git_describe_command = "git describe --tags --abbrev=4"

[project]
name = "adeploy"
dynamic = ["version"]
dependencies = [
  "colorama>=0.4.3",
  "Jinja2>=3.1,<4",
  "PyYAML>=6,<7",
  "ruamel.yaml>=0.16",
  "ruamel.yaml.clib>=0.2",
  "packaging>=20",
  "shortuuid>=1",
  "watchdog>=3,<5",
  "jq>=1.11,<2"
]
authors = [
  { name="Daniel Morlock", email="daniel.morlock@awesome-it.de" },
  { name="Daniel Bross", email="daniel.bross@awesome-it.de" },
  { name="Adrian Vielsack", email="adrian.vielsack@awesome-it.de" },
  { name="Philip Flohr", email="philip.flohr@awesome-it.de" }
]
description = "Universal deployment tool for Kubernetes that supports rendering and deployment of lightweight Jinja templated k8s manifests as well as complex Helm charts."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]

[project.scripts]
adeploy = "adeploy.main:main"

[project.urls]
Homepage = "https://awesome-it.de"
Source = "https://github.com/awesome-it/adeploy"
Issues = "https://github.com/awesome-it/adeploy/issues"
Documentation = "https://awesome-it.de/docs/adeploy/latest"
