apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}-{{ release }}-redis
  namespace: {{ namespace }}
  labels:        
    app.kubernetes.io/part-of: {{ name }}
    app.kubernetes.io/instance: {{ release }}
    app.kubernetes.io/component: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ name }}
      app.kubernetes.io/instance: {{ release }}
      app.kubernetes.io/component: redis
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ name }}
        app.kubernetes.io/instance: {{ release }}
        app.kubernetes.io/component: redis
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: main
          image: {{ redis.image }}:{{ version('redis') }}
          imagePullPolicy: Always
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping