versions:
  nginx: 1.22

secrets:
  # See https://github.com/awesome-it/adeploy#jinja-secret-functions
  registry: {{ create_docker_registry_secret(
               server='registry.awesome-it.de',
               username='sa_registry_ro',
               custom_cmd=True,
               password='cat secrets/my_secret_prod') }}

  my_secret: {{ create_secret(as_ref=True, custom_cmd=True, my_secret='cat secrets/my_secret_prod') }}