versions:
  nginx: 1.22

secrets:
  registry: {{ create_docker_registry_secret(
               server='registry.awesome-it.de',
               username='sa_registry_ro',
               password=from_shell_command('cat namespaces/playground/secrets/my_secret_prod')) }}

  # --8<-- [start:example-ref]
  my_secret: {{ create_secret(as_ref=True, my_secret=from_shell_command('cat namespaces/playground/secrets/my_secret_prod | head -n 1')) }}
  # --8<-- [end:example-ref]