apiVersion: v1
kind: Secret
metadata:
  name: {{ secret.get('name') }}
  {% if deployment.get('namespace', False) -%}
  namespace: {{ deployment.get('namespace') }}
  {%- endif %}
type: Opaque
data:
  {% for name, value in secret.get('data', {}).items() -%}
  {{ name }}: {{ value | base64_encode }}
  {%- endfor %}